FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

# Instalar curl
RUN apt-get update && apt-get install -y curl \
  && rm -rf /var/lib/apt/lists/*

# Instalar uv
RUN curl -Ls https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:/root/.cargo/bin:$PATH"

WORKDIR /app

# Copiar dependencias primero
COPY pyproject.toml uv.lock ./

# Instalar deps en el sistema (mejor para Docker)
RUN uv pip install --system -r pyproject.toml

# Copiar proyecto
COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
